# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"q\n\x12ImageLabelResponse\x12\x11\n\titeration\x18\x01 \x01(\x05\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x1a\n\x12ground_truth_label\x18\x03 \x01(\t\x12\x18\n\x10prediction_label\x18\x04 \x01(\t\"&\n\x11ImageLabelRequest\x12\x11\n\titeration\x18\x01 \x01(\x05\x32R\n\x11ImageLabelService\x12=\n\x12GetImagePrediction\x12\x12.ImageLabelRequest\x1a\x13.ImageLabelResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGELABELRESPONSE._serialized_start=15
  _IMAGELABELRESPONSE._serialized_end=128
  _IMAGELABELREQUEST._serialized_start=130
  _IMAGELABELREQUEST._serialized_end=168
  _IMAGELABELSERVICE._serialized_start=170
  _IMAGELABELSERVICE._serialized_end=252
# @@protoc_insertion_point(module_scope)
