# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ImageLabelServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImagePrediction = channel.unary_unary(
                '/ImageLabelService/GetImagePrediction',
                request_serializer=image__pb2.ImageLabelRequest.SerializeToString,
                response_deserializer=image__pb2.ImageLabelResponse.FromString,
                )


class ImageLabelServiceServicer(object):
    """Define the gRPC service
    """

    def GetImagePrediction(self, request, context):
        """RPC method to get image prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageLabelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImagePrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImagePrediction,
                    request_deserializer=image__pb2.ImageLabelRequest.FromString,
                    response_serializer=image__pb2.ImageLabelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageLabelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageLabelService(object):
    """Define the gRPC service
    """

    @staticmethod
    def GetImagePrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageLabelService/GetImagePrediction',
            image__pb2.ImageLabelRequest.SerializeToString,
            image__pb2.ImageLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
