# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loss.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nloss.proto\" \n\x0bLossRequest\x12\x11\n\titeration\x18\x01 \x01(\x05\"/\n\x0cLossResponse\x12\x11\n\titeration\x18\x01 \x01(\x05\x12\x0c\n\x04loss\x18\x02 \x01(\x02\x32\x39\n\nTrainModel\x12+\n\nTrainModel\x12\x0c.LossRequest\x1a\r.LossResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loss_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOSSREQUEST._serialized_start=14
  _LOSSREQUEST._serialized_end=46
  _LOSSRESPONSE._serialized_start=48
  _LOSSRESPONSE._serialized_end=95
  _TRAINMODEL._serialized_start=97
  _TRAINMODEL._serialized_end=154
# @@protoc_insertion_point(module_scope)
